In [1]:
import numpy as np 
import math
from sklearn import datasets
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn import preprocessing
from sklearn import metrics
from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import roc_auc_score
import matplotlib.pyplot as plt
from sklearn.metrics import roc_curve, auc
from sklearn.metrics import recall_score
from sklearn.metrics import precision_score
from sklearn.preprocessing import LabelBinarizer
from sklearn.metrics import f1_score
from scipy.stats import spearmanr

# Finding Correlation between Target and Features using Spearman correlation coefficient

In [2]:
def pearsoncorr(X, Y):
    covar = np.mean(Y*X)-(np.mean(Y)*np.mean(X))
    stddev_1 = np.sqrt(np.mean(Y**2)-(np.mean(Y))**2)
    stddev_2 = np.sqrt(np.mean(X**2)-np.mean(X)**2)
    corr_coeff = covar/(stddev_1*stddev_2)
    print("Pearson Correlation Coefficient:",corr_coeff)

In [3]:
sdataset = pd.read_csv('BSOM_DataSet_for_HW3.csv')
Xmcqs = sdataset.loc[:,['all_mcqs_avg_n20']].values
Xnbme = sdataset.loc[:,['all_NBME_avg_n4']].values
Xcbse1 = sdataset.loc[:,['CBSE_01']].values
Xcbse2 = sdataset.loc[:,['CBSE_02']].values
Xstep1 = sdataset.loc[:,['STEP_1']].values
XHA_final = sdataset.loc[:,['HA_final']].values
XHA_PI_AVG = sdataset.loc[:,['HA_PI_AVG_04']].values
XB2ENBME = sdataset.loc[:,['B2E_NBME_final']].values
XHDPIAVG = sdataset.loc[:,['HD_PI_AVG_15']].values
XHDIRATAVG = sdataset.loc[:,['HD_IRAT_AVG_02']].values
XBCRPIAVG = sdataset.loc[:,['BCR_PI_AVG_30']].values
XSAIRATAVG =sdataset.loc[:,['SA_IRAT_AVG_07']].values
XB2EIRATAVG =sdataset.loc[:,['B2E_IRAT_AVG_06']].values
XBCRIRATAVG =sdataset.loc[:,['BCR_IRAT_AVG_03']].values
XBCRANATMCQAVG =sdataset.loc[:,['BCR_ANAT_MCQ_AVG_02']].values
#target
yy = sdataset.loc[:,['LEVEL']]
level = {'A': 0,'B': 1,'C':2,'D':3} 
y_copy = [level[item] for item in yy.LEVEL]
y_copy = np.asarray(y_copy)
target = y_copy[:,None]

In [4]:
print("B/w target and HA_final:")
print(spearmanr(target,XHA_final))
print("B/w target and step1")
print(spearmanr(target,Xstep1))
print("B/w target and HAPIAVG")
print(spearmanr(target,XHA_PI_AVG))

print("B/w target and HDPIAVG")
print(spearmanr(target,XHDPIAVG))
print("B/w target and XHDIRATAVG")
print(spearmanr(target,XHDIRATAVG))
print("B/w target and BCRPIAVG")
print(spearmanr(target,XBCRPIAVG))
print("B/w target and SAIRATAVG")
print(spearmanr(target,XSAIRATAVG))
print("B/w target and XB2EIRATAVG")
print(spearmanr(target,XB2EIRATAVG))

print("B/w target and XBCRANATMCQAVG")
print(spearmanr(target,XBCRANATMCQAVG))

B/w target and HA_final:
SpearmanrResult(correlation=-0.46080943853350176, pvalue=2.1920581800321847e-07)
B/w target and step1
SpearmanrResult(correlation=-0.9412166544561835, pvalue=4.3582758063370176e-55)
B/w target and HAPIAVG
SpearmanrResult(correlation=-0.5172336574189177, pvalue=3.2475926121345915e-09)
B/w target and HDPIAVG
SpearmanrResult(correlation=-0.4901745276275143, pvalue=2.692016513883656e-08)
B/w target and XHDIRATAVG
SpearmanrResult(correlation=-0.3854009849505833, pvalue=2.106208033370216e-05)
B/w target and BCRPIAVG
SpearmanrResult(correlation=-0.5502290320965951, pvalue=1.892219091055297e-10)
B/w target and SAIRATAVG
SpearmanrResult(correlation=-0.5120986507360566, pvalue=4.9212014925915955e-09)
B/w target and XB2EIRATAVG
SpearmanrResult(correlation=-0.47226661490308897, pvalue=9.899515947883915e-08)
B/w target and XBCRANATMCQAVG
SpearmanrResult(correlation=-0.46564809726961476, pvalue=1.57248012152044e-07)


# Finding Correlation between Features using Pearson correlation coefficient

In [5]:

print("B/w mcqs and step1")
pearsoncorr(Xmcqs,Xstep1)
print("B/w cbse and BCRPIAVG")
pearsoncorr(Xcbse1,XBCRPIAVG)
print("B/w Xmcqs and BCRPIAVG")
pearsoncorr(Xmcqs,XBCRPIAVG)
print("B/w cbse and XSAIRATAVG")
pearsoncorr(Xcbse1,XSAIRATAVG)

print("B/w mcqs and HAPIAVG")
pearsoncorr(Xmcqs,XHA_PI_AVG)
pearsoncorr(Xnbme,XHDIRATAVG)
print("B/w nbme and HDPIAVG")
pearsoncorr(Xnbme,XHDPIAVG)
print("B/w step1 and cbse1")
pearsoncorr(Xcbse1,Xstep1)
print("B/w nbme and XHDIRATAVG")
pearsoncorr(Xnbme,XHDPIAVG)
print("B/w nbme and XHDIRATAVG")
pearsoncorr(Xnbme,XHDPIAVG)
print("B/w cbse and XB2EIRATAVG")
pearsoncorr(Xcbse1,XB2EIRATAVG)
print("B/w cbse and XBCRANATMCQAVG")
pearsoncorr(Xcbse1,XBCRANATMCQAVG)

print("B/w mcqs and HA_final:")
pearsoncorr(Xmcqs,XHA_final)


B/w mcqs and step1
Pearson Correlation Coefficient: 0.7027184782873007
B/w cbse and BCRPIAVG
Pearson Correlation Coefficient: 0.5721730984151181
B/w Xmcqs and BCRPIAVG
Pearson Correlation Coefficient: 0.8278558574743187
B/w cbse and XSAIRATAVG
Pearson Correlation Coefficient: 0.5476270395001492
B/w mcqs and HAPIAVG
Pearson Correlation Coefficient: 0.7087295432282957
Pearson Correlation Coefficient: 0.4495872358856143
B/w nbme and HDPIAVG
Pearson Correlation Coefficient: 0.7630822593495324
B/w step1 and cbse1
Pearson Correlation Coefficient: 0.5316958279960595
B/w nbme and XHDIRATAVG
Pearson Correlation Coefficient: 0.7630822593495324
B/w nbme and XHDIRATAVG
Pearson Correlation Coefficient: 0.7630822593495324
B/w cbse and XB2EIRATAVG
Pearson Correlation Coefficient: 0.44020939336032605
B/w cbse and XBCRANATMCQAVG
Pearson Correlation Coefficient: 0.4598059186444644
B/w mcqs and HA_final:
Pearson Correlation Coefficient: 0.665277846332941


In [6]:
def sigmoid(z):
    return  1/(1+np.exp(-z))

def build_model(X,neural_layer,input_dim,hidden_nodes,output_dim):
    model = {}
    for i in range(neural_layer):
        if i==0:
            continue
        elif i==1:
            #print("1st elif loop",i)
            model['W'+str(i)] =  np.random.randn(input_dim, hidden_nodes) / np.sqrt(input_dim) 
            model['b'+str(i)] =  np.zeros((1, hidden_nodes))
        elif i==neural_layer-1:
            #print("2nd if loop",i)
            model['W'+str(i)] = np.random.randn(hidden_nodes, output_dim) / np.sqrt(hidden_nodes)
            model['b'+str(i)] =  np.zeros((1, output_dim))
        else:
            #print("else loop",i)
            model['W'+str(i)] =  np.random.randn(hidden_nodes, hidden_nodes) / np.sqrt(hidden_nodes) 
            model['b'+str(i)] =  np.zeros((1, hidden_nodes))
    
        
    return model

def feed_forward(neural_layer,model, x):
    z={}
    a={}
    for i in range(1,neural_layer+1):
        
        # Forward propagation for layer 1
        if i==1:
            continue
        # Forward propagation for layer 2
        elif i==2:
            z[i] = x.dot(model['W'+str(i-1)]) + model['b'+str(i-1)]
            a[i] = sigmoid(z[i])
            #print("z2:",z2)
        # Forward propagation for other layer  
        else:
            z[i] = a[i-1].dot(model['W'+str(i-1)]) + model['b'+str(i-1)]
            a[i] = sigmoid(z[i])
            #print("z3:",z3)
    return a

def backprop(neural_layer,x,y,model,a,tri_Delta):
    #Lower delta error
    delt = {}
    for i in range(neural_layer,1,-1):
        #output layer  error 
        if i==neural_layer:
            delt[i] = a[i] - y
            
            tri_Delta['b'+str(i-1)] += np.sum(delt[i], axis=0, keepdims=True)
            tri_Delta['W'+str(i-1)] += (a[i-1].T).dot(delt[i])
            #print("db2:",db2)
            #print("dW2:",dW2)
             
        #Error in second layer 
        elif i==2:
            delt[i] = np.multiply(delt[i+1].dot(model['W'+str(i)].T),(a[i]*(1-a[i])))
            #print("del2:",del2)
            tri_Delta['b'+str(i-1)] += np.sum(delt[i], axis=0, keepdims=True)
            tri_Delta['W'+str(i-1)] += np.dot(x.T, delt[i])
        #Hidden layer error
        else:
            delt[i] = np.multiply(delt[i+1].dot(model['W'+str(i)].T),(a[i]*(1-a[i])))
            #print("del2:",del2)
            tri_Delta['b'+str(i-1)] += np.sum(delt[i], axis=0, keepdims=True)
            tri_Delta['W'+str(i-1)] += np.dot(a[i-1].T, delt[i])
    #print("delt:",delt)
    return tri_Delta

def calculate_loss(neural_layer,N,model,a,y_true,sum_cost):
    #sum_cost += np.sum((a[neural_layer]-y_true)**2)
    
    
    sum_cost +=np.sum((y_true*np.log(a[neural_layer]))+((1-y_true)*np.log(1-a[neural_layer])))
    #print("sum_cost",sum_cost)
    
    return sum_cost

def train(neural_layer,N,model, X_train, y_train,input_dim, reg_lambda, learning_rate,hidden_nodes):
    # Batch gradient descent
    done = False
    previous_loss = float('inf')
    iterations = 0
    
    losses = []
    #while done == False:  #comment out while performance testing
    while iterations < 500:
        scost=0
        tri_Delta={}
        for i in range(neural_layer):
            if i==0:
                continue
            elif i==1:
                #print("1st elif loop",i)
                tri_Delta['W'+str(i)] =  np.zeros((input_dim, hidden_nodes)) 
                tri_Delta['b'+str(i)] =  np.zeros((1, hidden_nodes))
            elif i==neural_layer-1:
                #print("2nd if loop",i)
                tri_Delta['W'+str(i)] = np.zeros((hidden_nodes, output_dim))
                tri_Delta['b'+str(i)] =  np.zeros((1, output_dim))
            else:
                #print("else loop",i)
                tri_Delta['W'+str(i)] =  np.zeros((hidden_nodes, hidden_nodes)) 
                tri_Delta['b'+str(i)] =  np.zeros((1, hidden_nodes))
            
        
        for row in zip(X_train, y_train):
            #feed forward
            a = feed_forward(neural_layer,model, row[0][None,:])
           
            tri_Delta = backprop(neural_layer,row[0][None,:],row[1][None,:],model,a,tri_Delta)
            
            #cost
            cost = calculate_loss(neural_layer,N,model, a,row[1][None,:], scost)
            
        #update weights and biases
        for i in range(1,neural_layer):
            model['W'+str(i)]-= learning_rate*((tri_Delta['W'+str(i)]/N) + (reg_lambda/N)* model['W'+str(i)])
            model['b'+str(i)]-= learning_rate*(tri_Delta['b'+str(i)]/N) 
        sc=0
        for nl in range(1,n_layer):
            sc+= np.sum(np.square(model['W'+str(nl)])) 
        loss = (-1/N)*cost+(reg_lambda/2*N)*sc
        #print("cost:",cost,"loss:",loss)
        losses.append(loss)
        if iterations%100==0:
            print ("Loss after iteration %i: %f" %(iterations, loss))  #uncomment once testing finished, return mod val to 1000
        if ( previous_loss-loss) < 0.000001:
            done = True
            #print("convergence i:",iterations,previous_loss-loss) 
            #break
        previous_loss = loss
        iterations += 1
    return model, losses

In [7]:

sdataset = pd.read_csv('BSOM_DataSet_for_HW3.csv')
X = sdataset.loc[:,['all_mcqs_avg_n20','all_NBME_avg_n4','CBSE_01','CBSE_02']].values
X1 = sdataset.loc[:,['all_mcqs_avg_n20','all_NBME_avg_n4','CBSE_01','CBSE_02','STEP_1']].values
X2 = sdataset.loc[:,['all_mcqs_avg_n20','all_NBME_avg_n4','CBSE_01','CBSE_02','SA_IRAT_AVG_07','STEP_1']].values
y = sdataset.loc[:,['LEVEL']].values

#Feature Scaling using Mean normalization 
mean_norm_X = (X-np.mean(X,axis=0))/(np.max(X,axis=0)-np.min(X,axis=0))
mean_norm_X1 = (X1-np.mean(X1,axis=0))/(np.max(X1,axis=0)-np.min(X1,axis=0))
mean_norm_X2 = (X1-np.mean(X1,axis=0))/(np.max(X1,axis=0)-np.min(X1,axis=0))
#One vs all y_train
concat=[]
for i in np.unique(y):
    one_vs_all_y=np.where(y==i,1,0)
    concat.extend(list(zip(*one_vs_all_y)))
actual_y= np.asarray(concat).T 

# Splitting the dataset into the Training set and Test set
X_train, X_test, y_train, y_test = train_test_split(mean_norm_X, actual_y, test_size = 1/3)
X1_train, X1_test, y1_train, y1_test = train_test_split(mean_norm_X1, actual_y, test_size = 1/3)
X2_train, X2_test, y2_train, y2_test = train_test_split(mean_norm_X2, actual_y, test_size = 1/3)
N,input_features = X_train.shape 
N,input_features1 = X1_train.shape
N,input_features2 = X2_train.shape
# output layer dimensionality 
output_dim = len(np.unique(y)) 
# learning rate for gradient descent
learning_rate = 0.6
hidden_nodes=5
reg_lambda = 0.001 # regularization strength
n_layer=3

In [8]:
def fscore(y_true, y_pred):
    f1_macro = f1_score(y_test, y_pred, average='macro')  
    print("F1 macro :" ,f1_macro)
    f1_micro  = f1_score(y_test, y_pred, average='micro')  
    print("F1 micro :" ,f1_micro)
    f1_weighted = f1_score(y_test, y_pred, average='weighted')  
    print("F1 weighted :" ,f1_weighted)
    f1 = f1_score(y_test, y_pred, average=None)
    print("F1 score :" ,f1)


In [9]:
model = build_model(X_train,n_layer,input_features,hidden_nodes,output_dim)
model, losses = train(n_layer,N,model,X_train, y_train,input_features, reg_lambda, learning_rate,hidden_nodes)


y_true = []
y_pred = []
for row in zip(X_test, y_test):
    a = feed_forward(n_layer,model, row[0][None,:])
    y_pred.append(np.argmax(a[n_layer]))
    y_true.append(np.argmax(row[1][None,:]))
print("y_true",y_true)
print("y_pred",y_pred)
print(classification_report(y_true, y_pred,target_names=['A', 'B', 'C','D']))   
print("confusion matrix:",confusion_matrix(y_true, y_pred))
print("Accuracy:",accuracy_score(y_true, y_pred))
lb = LabelBinarizer()
lb.fit(y_true)
y_t= lb.transform(y_true)
y_p = lb.transform(y_pred)
fscore(y_t,y_p)
print("ROC AUC score",metrics.roc_auc_score(y_t,y_p))

Loss after iteration 0: 0.264604
Loss after iteration 100: 0.717414
Loss after iteration 200: 2.447373
Loss after iteration 300: 3.822840
Loss after iteration 400: 4.903479
y_true [2, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 2, 1, 1, 2, 3, 0, 1, 1, 1, 2, 1, 1, 2, 3, 1, 0, 2, 2, 0, 1, 1, 1, 1, 1, 0, 3, 1, 1]
y_pred [2, 1, 0, 0, 2, 0, 0, 1, 1, 0, 0, 2, 1, 0, 2, 2, 0, 0, 1, 1, 2, 0, 2, 2, 2, 1, 0, 2, 1, 0, 0, 1, 0, 1, 0, 0, 2, 1, 2]
             precision    recall  f1-score   support

          A       0.50      1.00      0.67         8
          B       0.91      0.48      0.62        21
          C       0.50      0.86      0.63         7
          D       0.00      0.00      0.00         3

avg / total       0.68      0.62      0.59        39

confusion matrix: [[ 8  0  0  0]
 [ 8 10  3  0]
 [ 0  1  6  0]
 [ 0  0  3  0]]
Accuracy: 0.6153846153846154
F1 macro : 0.4808114035087719
F1 micro : 0.6153846153846154
F1 weighted : 0.586650922177238
F1 score : [0.66666667 0.625      0.63157895 0.        ]

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


# Question 3a Adding one feature and 3c metrics

In [10]:
model = build_model(X1_train,n_layer,input_features1,hidden_nodes,output_dim)
model, losses = train(n_layer,N,model,X1_train, y1_train,input_features1, reg_lambda, learning_rate,hidden_nodes)


y_true = []
y_pred = []
for row in zip(X1_test, y1_test):
    a = feed_forward(n_layer,model, row[0][None,:])
    y_pred.append(np.argmax(a[n_layer]))
    y_true.append(np.argmax(row[1][None,:]))
print("y_true",y_true)
print("y_pred",y_pred)
print(classification_report(y_true, y_pred,target_names=['A', 'B', 'C','D']))   
print("confusion matrix:",confusion_matrix(y_true, y_pred))
print("Accuracy:",accuracy_score(y_true, y_pred))
lb = LabelBinarizer()
lb.fit(y_true)
y_t= lb.transform(y_true)
y_p = lb.transform(y_pred)

print("ROC AUC score",metrics.roc_auc_score(y_t,y_p))

Loss after iteration 0: 0.415760
Loss after iteration 100: 0.927066
Loss after iteration 200: 2.811294
Loss after iteration 300: 4.549292
Loss after iteration 400: 6.258585
y_true [3, 2, 0, 3, 2, 3, 1, 0, 0, 2, 1, 1, 2, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 2, 1, 1, 2, 0, 0, 1, 1, 2, 0, 0, 1, 2, 2, 0, 2]
y_pred [2, 1, 0, 2, 1, 2, 1, 0, 0, 2, 1, 1, 2, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 2, 0, 1, 2, 0, 0, 1, 1, 2, 0, 0, 1, 2, 2, 0, 2]
             precision    recall  f1-score   support

          A       0.92      0.92      0.92        13
          B       0.80      0.92      0.86        13
          C       0.73      0.80      0.76        10
          D       0.00      0.00      0.00         3

avg / total       0.76      0.82      0.79        39

confusion matrix: [[12  1  0  0]
 [ 1 12  0  0]
 [ 0  2  8  0]
 [ 0  0  3  0]]
Accuracy: 0.8205128205128205
ROC AUC score 0.798607427055703


C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


# Question 3b Adding another features and 3c metrics

In [11]:
model = build_model(X2_train,n_layer,input_features2,hidden_nodes,output_dim)
model, losses = train(n_layer,N,model,X2_train, y2_train,input_features2, reg_lambda, learning_rate,hidden_nodes)

y_true = []
y_pred = []
for row in zip(X2_test, y2_test):
    a = feed_forward(n_layer,model, row[0][None,:])
    y_pred.append(np.argmax(a[n_layer]))
    y_true.append(np.argmax(row[1][None,:]))
print("y_true",y_true)
print("y_pred",y_pred)
print(classification_report(y_true, y_pred,target_names=['A', 'B', 'C','D']))   
print("confusion matrix:",confusion_matrix(y_true, y_pred))
print("Accuracy:",accuracy_score(y_true, y_pred))
lb = LabelBinarizer()
lb.fit(y2_test)
y_t= lb.transform(y_true)
y_p = lb.transform(y_pred)

print("ROC AUC score",metrics.roc_auc_score(y_t,y_p))


Loss after iteration 0: 0.392501
Loss after iteration 100: 1.210299
Loss after iteration 200: 3.005351
Loss after iteration 300: 4.391723
Loss after iteration 400: 5.829362
y_true [2, 0, 2, 0, 2, 3, 2, 0, 1, 1, 0, 2, 0, 0, 1, 1, 0, 0, 1, 1, 2, 0, 1, 1, 1, 0, 1, 0, 1, 2, 1, 0, 0, 1, 2, 0, 3, 1, 0]
y_pred [1, 0, 1, 0, 2, 2, 1, 0, 1, 2, 0, 2, 1, 0, 1, 1, 0, 0, 1, 2, 2, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 2, 1, 0, 2, 1, 0]
             precision    recall  f1-score   support

          A       0.93      0.93      0.93        15
          B       0.62      0.71      0.67        14
          C       0.38      0.38      0.38         8
          D       0.00      0.00      0.00         2

avg / total       0.66      0.69      0.68        39

confusion matrix: [[14  1  0  0]
 [ 1 10  3  0]
 [ 0  5  3  0]
 [ 0  0  2  0]]
Accuracy: 0.6923076923076923
ROC AUC score 0.6974577572964671


C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
